name: Hello World Workflow

# Defines when the action will run.
on: [push]

# Jobs that the workflow will execute
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # A step to run a script command
    - name: Hello World
      run: echo "Hello, World! My first GitHub Actions workflow!"
